spring:
## database connection
  datasource:
    platform: postgres
    driver-class-name: org.postgresql.Driver
    url: ${DB_URL:jdbc:postgresql://localhost:5432/postgres}
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:postgres}
    maximum-pool-size: 400
    minimum-idle: 100

  jpa:
    show-sql: false
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: none
    properties:
      jdbc:
        batch_size: 10000
  sql:
    init:
      platform: postgres
      mode: always

