spring:
  application:
    name: unitTest

## database connection
  datasource:
    platform: H2
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:game_sales
    username: ${DB_USERNAME:sa}

  jpa:
    show-sql: true
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: none
    properties:
      jdbc:
        batch_size: 500
  sql:
    init:
      platform: H2
      mode: always
  h2:
    console:
      enabled: true