-- public.game_sales definition

-- Drop table

DROP TABLE IF EXISTS public.game_sales;

CREATE TABLE public.game_sales (
	id int8 NOT NULL GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE),
	game_no int4 NULL,
	game_name varchar(20) NULL,
	game_code varchar(5) NULL,
	"type" int4 NULL,
	cost_price float8 NULL,
	tax float8 NULL,
	sale_price float8 NULL,
	date_of_sale timestamp(6) NULL,
	ingestion_id int8 NOT NULL,
	created timestamp(6) DEFAULT CURRENT_TIMESTAMP,
	last_modified timestamp(6) DEFAULT CURRENT_TIMESTAMP,
	CONSTRAINT game_sales_cost_price_check CHECK ((cost_price <= (100)::double precision)),
	CONSTRAINT game_sales_game_no_check CHECK (((game_no <= 100) AND (game_no >= 1))),
	CONSTRAINT game_sales_pkey PRIMARY KEY (id),
	CONSTRAINT game_sales_type_check CHECK (((type <= 2) AND (type >= 1)))
);


-- This is for logging purpose.
DROP TABLE IF EXISTS public.ingestion_history;

CREATE TABLE public.ingestion_history (
	id int8 NOT NULL GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE),
	"source" varchar NULL,
	created timestamp(6) NULL DEFAULT CURRENT_TIMESTAMP,
	last_modified timestamp(6) NULL DEFAULT CURRENT_TIMESTAMP,
	CONSTRAINT ingestion_history_pkey PRIMARY KEY (id)
);

ALTER TABLE public.game_sales ADD CONSTRAINT game_sales_ingestion_history_fk FOREIGN KEY (ingestion_id) REFERENCES public.ingestion_history(id);

